substitutions:
  _APP: github.com/brkelley/squad

timeout: 1000s
steps:
- name: golang
  args: ['go', 'build', '.']
  env:
    - 'FIREBASE_CONFIG_SERVICE_ACCOUNT=${_FIREBASE_CONFIG_SERVICE_ACCOUNT}'
    - 'FIREBASE_CONFIG_CLIENT=${_FIREBASE_CONFIG_CLIENT}'
- name: node
  entrypoint: npm
  args: ["ci", "--prefix", "client"]
  env:
    - 'FIREBASE_CONFIG_SERVICE_ACCOUNT=${_FIREBASE_CONFIG_SERVICE_ACCOUNT}'
    - 'FIREBASE_CONFIG_CLIENT=${_FIREBASE_CONFIG_CLIENT}'
- name: node
  entrypoint: npm
  args: ["run", "start", "--prefix", "client"]
  env:
    - 'FIREBASE_CONFIG_SERVICE_ACCOUNT=${_FIREBASE_CONFIG_SERVICE_ACCOUNT}'
    - 'FIREBASE_CONFIG_CLIENT=${_FIREBASE_CONFIG_CLIENT}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--promote"]
