steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'FIREBASE_CONFIG_SERVICE_ACCOUNT=${_FIREBASE_CONFIG_SERVICE_ACCOUNT}'
    - 'FIREBASE_CONFIG=${_FIREBASE_CONFIG}'
- name: node
  entrypoint: npm
  args: ["install"]
- name: node
  entrypoint: npm
  args: ["install", "--prefix", "client"]
- name: node
  entrypoint: npm
  args: ["run", "client"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--promote"]
