substitutions:
  _APP: github.com/brkelley/squad

timeout: 1000s
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args: ['-c', 'printenv > config.env']
  env:
  - 'FIREBASE_CONFIG_CLIENT=$_FIREBASE_CONFIG_CLIENT'
  - 'FIREBASE_CONFIG_SERVICE_ACCOUNT=$_FIREBASE_CONFIG_SERVICE_ACCOUNT'
- name: golang
  args: ['go', 'build', '.']
- name: node
  entrypoint: npm
  args: ["ci", "--prefix", "client"]
- name: node
  entrypoint: npm
  args: ["run", "start", "--prefix", "client"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--promote"]
