version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/squad # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-server-npm
          command: npm install
      - run:
          name: install-client-npm
          command: npm install --prefix client
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            - ./client/node_modules
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
  deploy:
    working_directory: ~/squad # directory where steps will run
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: bundle-client
          command: npm run client
      - run: |
          echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: deploy-gcloud
          command: 'gcloud app deploy --promote'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # Only deploy once the build job has completed
          filters:
            branches:
              only: master # Only deploy on the master branch
