// pro play metadata
export const SET_MATCHES = 'SET_MATCHES';
export const SET_TEAMS = 'SET_TEAMS';

// predictions
export const SET_PREDICTION_MAP = 'SET_PREDICTION_MAP';
export const SET_PREDICTION_AT_KEY = 'SET_PREDICTION_AT_KEY';
export const SET_PREDICTION = 'SET_PREDICTION';
export const SET_PREDICTION_FILTER = 'SET_PREDICTION_FILTER';
export const SET_UNSAVED_PREDICTIONS = 'SET_UNSAVED_PREDICTIONS';
export const RESET_UNSAVED_PREDICTIONS = 'RESET_UNSAVED_PREDICTIONS';
export const SET_OR_UPDATE_PREDICTION_SCORE = 'SET_OR_UPDATE_PREDICTION_SCORE';

// users
export const SET_USERS_METADATA = 'SET_USERS_METADATA';
export const SET_USER = 'SET_USER';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_DISCORD_INFO = 'SET_DISCORD_INFO';
